# permissions for end users to view hyperfoils.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hyperfoil-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hyperfoil-operator
    app.kubernetes.io/part-of: hyperfoil-operator
    app.kubernetes.io/managed-by: kustomize
  name: hyperfoil-viewer-role
rules:
- apiGroups:
  - hyperfoil.io
  resources:
  - hyperfoils
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hyperfoil.io
  resources:
  - hyperfoils/status
  verbs:
  - get
